# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rack-mongrel2}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Huckstep"]
  s.date = %q{2010-10-24}
  s.description = %q{A Rack handler for the Mongrel2 web server, by Zed Shaw. http://mongrel2.org/}
  s.email = %q{darkhelmet@darkhelmetlive.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".rvmrc",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "example/mongrel2.conf",
     "example/sinatra/app.rb",
     "example/sinatra/config.ru",
     "lib/mongrel2/connection.rb",
     "lib/mongrel2/request.rb",
     "lib/mongrel2/response.rb",
     "lib/rack/handler/mongrel2.rb",
     "rack-mongrel2.gemspec",
     "spec/rack-mongrel2_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/darkhelmet/rack-mongrel2}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{The only Mongrel2 Rack handler you'll ever need.}
  s.test_files = [
    "spec/rack-mongrel2_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<yajl-ruby>, ["~> 0.7.8"])
      s.add_runtime_dependency(%q<zmq>, ["~> 2.0.9"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.4.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.0.1"])
      s.add_development_dependency(%q<yard>, ["~> 0.6.1"])
    else
      s.add_dependency(%q<yajl-ruby>, ["~> 0.7.8"])
      s.add_dependency(%q<zmq>, ["~> 2.0.9"])
      s.add_dependency(%q<jeweler>, ["~> 1.4.0"])
      s.add_dependency(%q<rspec>, ["~> 2.0.1"])
      s.add_dependency(%q<yard>, ["~> 0.6.1"])
    end
  else
    s.add_dependency(%q<yajl-ruby>, ["~> 0.7.8"])
    s.add_dependency(%q<zmq>, ["~> 2.0.9"])
    s.add_dependency(%q<jeweler>, ["~> 1.4.0"])
    s.add_dependency(%q<rspec>, ["~> 2.0.1"])
    s.add_dependency(%q<yard>, ["~> 0.6.1"])
  end
end

